### PR TITLE
feat(torch): native models can load weights from any jit file

### PR DESCRIPTION
**Pull request by BynaryCobweb**
Added a function "copy_weights" to copy common weights from a
script module to a nn::Module. Weights that do not match are
ignored, and printed to the logs as warning.

### CODE REVIEW

**Review by fantes — APPROVED** [review]

**Comment by beniz** [comment]
Great, though I'd have weights that do not match generate an error instead, what do you think ?

**Comment by fantes** [comment]
> Great, though I'd have weights that do not match generate an error instead, what do you think ?

In case of finetuning, maybe that should not be an error ?

**Comment by BynaryCobweb** [comment]
> > Great, though I'd have weights that do not match generate an error instead, what do you think ?
> 
> In case of finetuning, maybe that should not be an error ?

The point of this change is that we can load only some of the weights when finetuning.
I can add a parameter so that we throw when not finetuning, and we don't throw otherwise

**Review by sileht — APPROVED** [review]

**Comment by BynaryCobweb** [comment]
@Mergifyio update

**Pull request merged**
