### PR TITLE
fix: docker cpu link in readme

### PR DESCRIPTION
**Pull request by beniz**

### CODE REVIEW

**Comment by beniz** [comment]
Unfortunately the issue I was trying to solve remains: 
image

**Review by sileht — APPROVED** [review]
For some reason, the cpu image doesn't have the docker architecture set.

You can compare https://hub.docker.com/r/jolibrain/deepdetect_cpu/tags?page=1&ordering=last_updated and https://hub.docker.com/r/jolibrain/deepdetect_gpu/tags?page=1&ordering=last_updated

**Comment by sileht** [comment]
This is related to ubuntu 20.04 I guess

**Comment by beniz** [comment]
OK, interestingly the `ci:master` build has it, https://hub.docker.com/layers/jolibrain/deepdetect_cpu/ci-master/images/sha256-e1e76c54668053b7b328a8d7bdd6715e9e89a7ac9c6b7793f93238931c152317?context=explore we'll see how this goes!

**Review by Bycob — APPROVED** [review]

**Pull request merged**
