### PR TITLE
fix: torch backend CPU build and tests

### PR DESCRIPTION
**Pull request by beniz**

### CODE REVIEW

**Review by fantes — APPROVED** [review]

**Comment by fantes** [comment]
@Mergifyio rebase

**Review by BynaryCobweb — APPROVED** [review]

**Comment by sileht** [comment]
@mergifyio update

**Comment by sileht** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio rebase

**Pull request merged**
