### PR TITLE
chore(torch): push bounds for pytorch test

### PR DESCRIPTION
**Pull request by BynaryCobweb**

### CODE REVIEW

**Comment by BynaryCobweb** [comment]
#1143 was not enough

**Review by beniz — APPROVED** [review]

**Review by fantes — APPROVED** [review]

**Comment by fantes** [comment]
@Mergifyio rebase

**Comment by fantes** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio update

**Comment by sileht** [comment]
@Mergifyio rebase

**Comment by fantes** [comment]
@Mergifyio rebase

**Comment by fantes** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio rebase

**Pull request merged**
