### PR TITLE
BERT finetuning (classification + language model)

### PR DESCRIPTION
**Pull request by BynaryCobweb**
- Add training with pytorch backend
- Finetune and test BERT-based text classifiers
- Finetune language models using word masking

<!> When tracing models, use pytorch 1.1 and pytorch-transformers 1.1
```
pip3 install torch==1.1 pytorch-transformers==1.1
```

### Added parameters
- Text Input Connector

| Parameter | Type | Optional | Default | Description |
| -- | -- | -- | -- | -- |
|  ordered_words  | bool | yes | false | word-based processing with positionnal information |
| wordpiece_tokens | bool | yes | false | if vocabulary contains partial words. Words can be split into multiple tokens. |
| punctuation_tokens | bool | yes | false | Treat each punctuation sign as a token. (if false, punctuation is stripped from input)  |

- Torch MLLib

| Parameter | Type | Optional | Default | Description |
| -- | -- | -- | -- | -- |
| self_supervised | string | yes | "" | self-supervised mode: "mask" for masked language model *[TODO Add options : "next" = Next token prediction for GPT2?]* |
| embedding_size | int | yes | 768 | embedding size for NLP models |
| freeze_traced | bool | yes | false | Freeze the traced part of the net during finetuning (e.g. for classification) |

### CODE REVIEW

**Comment by BynaryCobweb** [comment]
## TODO before merge
- [ ] Improve TxtInputConnector support for unsupervised/self-supervised datasets (ie without classes)
- [ ] Fix TxtInputConnector regenerating vocab during finetuning

**Comment by BynaryCobweb** [comment]
# Example: Finetune language model
* Trace pytorch pretrained bert
```
pip3 install --user pytorch-transformers==1.1
mkdir lm_training
./trace_pytorch_transformers.py bert_masked_lm -vo lm_training --vocab
```
* Run dede
* Start the service
```
curl -X PUT "http://localhost:8080/services/torch_bert_lm" -d '{
    "description": "BERT language model finetuning on News20 ",
    "mllib": "torch",
    "model": {
        "repository": "./classif_training/"
    },
    "parameters": {
        "input": {
            "connector": "txt",
            "ordered_words": true,
            "wordpiece_tokens": true,
            "punctuation_tokens": true,
            "width": 512
        },
        "mllib": {
            "masked_lm": true,
            "finetuning": true,
            "gpu": true
        }
    },
    "type": "supervised"
}
'
```
* Train the model on news20 dataset
```
curl -X POST "http://localhost:8080/predict" -d '{
    "service": "torch_bert_lm", 
    "parameters": { 
         "mllib": {
            "iterations":3000,
            "test_interval":250,
            "base_lr":1e-5,
            "batch_size":4,
            "iter_size":8,
            "test_batch_size":4,
            "save_period":250,
            "solver_type":"ADAM"
        },
        "input": {
            "shuffle":true,
            "test_split":0.03
        },
        "output": {
            "measure":["acc", "acc-5"]
        }
    }, 
    "data": ["/opt/data/news20/train/"]
}
'
```

**Comment by beniz** [comment]
When running:
```
./trace_pytorch_transformers.py bert -vo classif_training --vocab
```

I get:

```
INFO:pytorch_transformers.file_utils:copying /tmp/tmpopsk80eg to cache at /home/beniz/.cache/torch/pytorch_transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
INFO:pytorch_transformers.file_utils:creating metadata file for /home/beniz/.cache/torch/pytorch_transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
INFO:pytorch_transformers.file_utils:removing temp file /tmp/tmpopsk80eg
INFO:pytorch_transformers.modeling_utils:loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at /home/beniz/.cache/torch/pytorch_transformers/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
INFO:pytorch_transformers.modeling_utils:Weights from pretrained model not used in BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
/home/beniz/.local/lib/python3.5/site-packages/torch/jit/__init__.py:914: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Not within tolerance rtol=1e-05 atol=1e-05 at input[0, 411, 26416] (-0.26612165570259094 vs. -0.2661484479904175) and 15297 other locations (0.00%)
  check_tolerance, _force_outplace, True, _module_class)
INFO:root:Saving to classif_training/bert-pretrained.pt
Traceback (most recent call last):
  File "/home/beniz/projects/deepdetect/dev/deepdetect/tools/torch/trace_pytorch_transformers.py", line 137, in <module>
    traced_model.save(filename)
  File "/home/beniz/.local/lib/python3.5/site-packages/torch/jit/__init__.py", line 1550, in save
    return self._c.save(*args, **kwargs)
RuntimeError: [enforce fail at inline_container.cc:319] . PytorchStreamWriter failed opening archive.
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7ff703d0be17 in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamWriter::valid(char const*) + 0xe6 (0x7ff6a0e8a906 in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamWriter::PyTorchStreamWriter(std::string, std::ostream*) + 0x74d (0x7ff6a0e8db5d in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #3: torch::jit::ExportModule(torch::jit::script::Module const&, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&) + 0x10d (0x7ff6a1f2edcd in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x4c8dcf (0x7ff700ff7dcf in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x1d3f04 (0x7ff700d02f04 in /home/beniz/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #6: PyCFunction_Call + 0x77 (0x4ea137 in /usr/bin/python3)
frame #7: PyEval_EvalFrameEx + 0x6bd3 (0x53d353 in /usr/bin/python3)
frame #8: /usr/bin/python3() [0x53fc97]
frame #9: PyEval_EvalFrameEx + 0x5513 (0x53bc93 in /usr/bin/python3)
frame #10: /usr/bin/python3() [0x53fc97]
frame #11: PyEval_EvalCode + 0x1f (0x5409bf in /usr/bin/python3)
frame #12: /usr/bin/python3() [0x60cb42]
frame #13: PyRun_FileExFlags + 0x9a (0x60efea in /usr/bin/python3)
frame #14: PyRun_SimpleFileExFlags + 0x1bc (0x60f7dc in /usr/bin/python3)
frame #15: Py_Main + 0x456 (0x640256 in /usr/bin/python3)
frame #16: main + 0xe1 (0x4d0001 in /usr/bin/python3)
frame #17: __libc_start_main + 0xf0 (0x7ff70a5e3830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #18: _start + 0x29 (0x5d6999 in /usr/bin/python3)
```

**Comment by beniz** [comment]
Is the vocabulary matched against the wildcard tokens of BERT (the '##' tokens) ? From line https://github.com/jolibrain/deepdetect/blob/09d8ca1b6d3935d66c065a2abc81c37b8022ec3e/src/backends/torch/torchinputconns.cc#L198 it seems that the vocab is matched only exactly, is this correct ?

**Comment by beniz** [comment]
>     * Add vocabulary generation with BPE if finetuning = false

What would be needed to train a model from scratch with a new vocabulary ?

**Comment by beniz** [comment]
> "save_period":250,

Please replace with `test_interval` that is the default name in DD API.

**Comment by beniz** [comment]
>  "width": 512

The txt input connector already defines `sequence` for the max character sequence size, maybe we'd like to use the same here.

**Comment by beniz** [comment]
> Example: Finetune a classification model

This fails for me, with error:
```
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"\narguments for call are not valid:\n  \n  for operator aten::mean(Tensor self) -> Tensor:\n  expected at most 1 arguments but found 3 positional arguments.\n 
```
and server log:
```
[2019-09-25 06:50:06.470] [api] [info] Running DeepDetect HTTP server on 10.10.77.61:8501
[2019-09-25 06:50:09.859] [torch_bert_training] [info] loaded vocabulary of size=30522
[2019-09-25 06:50:11.417] [torch_bert_training] [info] Loading ml model from file /data1/beniz/torch_models/news20/bert-pretrained.pt.
[2019-09-25 06:50:12.942] [torch_bert_training] [error] service creation call failed
[2019-09-25 06:50:12.944] [api] [error] 10.10.77.61 "PUT /services/torch_bert_training" 500 3120
```

**Comment by BynaryCobweb** [comment]
> Is the vocabulary matched against the wildcard tokens of BERT (the '##' tokens) ? From line
> 
> https://github.com/jolibrain/deepdetect/blob/09d8ca1b6d3935d66c065a2abc81c37b8022ec3e/src/backends/torch/torchinputconns.cc#L198
> it seems that the vocab is matched only exactly, is my understanding correct ?

Tokenization (including wordpiece) is done in `src/txtinputfileconn.cc:349` (see also: `WordpieceTokenizer::append_input()`). Here we just convert the previously found tokens to ids.

**Comment by BynaryCobweb** [comment]
> > ```
> > * Add vocabulary generation with BPE if finetuning = false
> > ```
> 
> What would be needed to train a model from scratch with a new vocabulary ?

The model has to be traced without initial weights:

**Pull request merged**
