### PR TITLE
fix: fix split_data in csvts connector

### PR DESCRIPTION
**Pull request by beniz**
chore: in-code function documentation for csv and csvts connectors

### CODE REVIEW

**Review by fantes — APPROVED** [review]

**Comment by sileht** [comment]
The commit title doesn't reflex the real change.

Can you change it to: `chore: in-code function documentation for csv and csvts connectors`

**Comment by beniz** [comment]
> The commit title doesn't reflex the real change.
> 
> Can you change it to: `chore: in-code function documentation for csv and csvts connectors` ?

FYI, the important fix is here: https://github.com/jolibrain/deepdetect/blob/285c6322e6df4c9ada948dacb78eb3b780e8386e/src/csvtsinputfileconn.cc#L183

Want 2 commits ?

**Comment by sileht** [comment]
It's always better to have two commits. In case of we need to revert it, we don't revert your cleanup :) 
And also the changelog for the release will be cleaner.

**Comment by sileht** [comment]
Let's say, it's OK for this one.

**Pull request merged**
