### PR TITLE
feat(timeseries): MAPE, sMAPE, MASE, OWA metrics

### PR DESCRIPTION
**Pull request by fantes**
this PR adds timeseries specific metrics , ie MAPE (output.metrics.mape) sMAPE (as output.metrics.smape) MASE (as output.metrics.mase) and OWA (as output.metrics.owa); see https://arxiv.org/abs/1905.10437 for equations

### CODE REVIEW

**Comment by beniz** [comment]
Don't forget updating the api doc !

**Comment by fantes** [comment]
> Don't forget updating the api doc !

done

**Review by BynaryCobweb — APPROVED** [review]

**Comment by beniz** [comment]
> > Don't forget updating the api doc !
> 
> done

Thanks, can we add these metrics to the existing timeseries unit tests by any chance ?

**Comment by fantes** [comment]
> > > Don't forget updating the api doc !
> > 
> > 
> > done
> 
> Thanks, can we add these metrics to the existing timeseries unit tests by any chance ?

ok, done

**Pull request merged**
