### PR TITLE
chore(cuda): support for Ampere GPU builds

### PR DESCRIPTION
**Pull request by beniz**

### CODE REVIEW

**Comment by beniz** [comment]
Builds should be fixed with #1247

**Review by Bycob — APPROVED** [review]

**Comment by fantes** [comment]
@Mergifyio rebase

**Review by fantes — APPROVED** [review]

**Comment by beniz** [comment]
TRT docker builds appear to fail running (but build OK), and this might be related to TRT version, see #1284 as well.

**Comment by fantes** [comment]
@Mergifyio rebase

**Comment by fantes** [comment]
@Mergifyio rebase

**Pull request merged**
