### PR TITLE
Updated dlib to 19.18

### PR DESCRIPTION
**Pull request by cchadowitz-pf**

### CODE REVIEW

**Comment by beniz** [comment]
Thanks, let us know if/when ready to merge.

**Comment by cchadowitz-pf** [comment]
Will do - looking to add a bit more functionality at the same time to support one additional network architecture.

**Comment by cchadowitz-pf** [comment]
I will open a separate PR for the additional network architecture and associated changes, as it's turned out to be more involved than I expected :) This is set to go as is.

**Comment by beniz** [comment]
Thanks for the contrib! You'd need to rebase to master in order to get the tests to pass, due to some recent fixes on the `master` branch.

**Comment by cchadowitz-pf** [comment]
Thanks, looks like the travis build passed, hopefully the jenkins one does too :)

**Comment by beniz** [comment]
Hi, I'm getting the following error when building on 18.04:
```
In file included from /home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix.h:19:0,
                 from /home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/libsvm_io.h:12,
                 from /home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io.h:6,
                 from /home/beniz/code/deepdetect/src/backends/dlib/dlibinputconns.h:27,
                 from /home/beniz/code/deepdetect/src/imginputfileconn.h:679,
                 from /home/beniz/code/deepdetect/src/services.h:29,
                 from /home/beniz/code/deepdetect/src/apistrategy.h:26,
                 from /home/beniz/code/deepdetect/src/deepdetect.h:25,
                 from /home/beniz/code/deepdetect/src/deepdetect.cc:22:
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In func
tion ‘std::complex<float> dlib::blas_bindings::cblas_dot(int, const std::complex<float>*, int, const std::complex<floa
t>*, int)’:
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:359:81: error: cannot convert ‘float*’ to ‘openblas_complex_float* {aka __complex__ float*}’ for argument ‘6’ to ‘void cblas_cdotu_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)’
             cblas_cdotu_sub(N, (float*)X, incX, (float*)Y, incY, (float*)&result);
                                                                                 ^
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function ‘std::complex<double> dlib::blas_bindings::cblas_dot(int, const std::complex<double>*, int, const std::complex<double>*, int)’:
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:368:84: error: cannot convert ‘double*’ to ‘openblas_complex_double* {aka __complex__ double*}’ for argument ‘6’ to ‘void cblas_zdotu_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)’
             cblas_zdotu_sub(N, (double*)X, incX, (double*)Y, incY, (double*)&result);
                                                                                    ^
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function ‘std::complex<float> dlib::blas_bindings::cblas_dotc(int, const std::complex<float>*, int, const std::complex<float>*, int)’:
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:379:81: error: cannot convert ‘float*’ to ‘openblas_complex_float* {aka __complex__ float*}’ for argument ‘6’ to ‘void cblas_cdotc_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)’
             cblas_cdotc_sub(N, (float*)X, incX, (float*)Y, incY, (float*)&result);
                                                                                 ^
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function ‘std::complex<double> dlib::blas_bindings::cblas_dotc(int, const std::complex<double>*, int, const std::complex<double>*, int)’:
/home/beniz/code/deepdetect/build_dlib_19.18/dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:388:84: error: cannot convert ‘double*’ to ‘openblas_complex_double* {aka __complex__ double*}’ for argument ‘6’ to ‘void cblas_zdotc_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)’
             cblas_zdotc_sub(N, (double*)X, incX, (double*)Y, incY, (double*)&result);
```

I guess this is related to the conflict with cblas used in Caffe.

**Comment by cchadowitz-pf** [comment]
Yes, that's the same error - I've been looking into it and it's related to how OpenBLAS specifically defines those particular APIs (vs the standard BLAS spec). I've been trying to get a good way to resolve it in 18.04 (which I've got) without breaking it for 16.04. I suspect that's partially due to the OpenBLAS version difference between the two (0.2.18 vs 0.2.20).

The changes in this PR though shouldn't have triggered the issue, and I suspect that the previous DeepDetect builds would have had the same error in 18.04 when enabling both Caffe and Dlib.

As I'm writing this I'm realizing that since the issue only occurs when *both* dlib and caffe are enabled, perhaps there's a situation where dlib is finding a different cblas.h from caffe that is tripping things up, and there really is a fix that involves shuffling include order/paths....

**Comment by beniz** [comment]
OK, if that's a complicated issue, in the meantime we could decide that dlib and caffe cannot be built together. Another test might be to switch the caffe build to using atlas and see whether the error still occurs.

**Comment by cchadowitz-pf** [comment]
True - or at the very least, we could decide that dlib+caffe can only be built together on 16.04 *or* 18.04 (depending on whether I include the fix or not) and not both...

**Comment by cchadowitz-pf** [comment]
More info - it seems that when nothing else is including `cblas.h`, dlib declares the prototypes for the CBLAS calls used by the BLAS bindings (correctly, according to the BLAS standard). However, when something else has already included a `cblas.h` (e.g. Caffe), dlib defers to those prototypes. 
Since we're using OpenBLAS, Caffe is including the `cblas.h` from OpenBLAS. This seems to incorrectly define those calls (uses `openblas_complex_float` instead of `float`, for example), which causes this error in the newer GCC on Ubuntu 18.04. When I force dlib to declare the prototypes regardless of whether another `cblas.h` has been included, the issue disappears.

How would you feel about dlib support (going forward) only supporting say 18.04?

**Comment by beniz** [comment]
> How would you feel about dlib support (going forward) only supporting say 18.04?

Thanks for the update! Fine with me as long as we document it somewhere :) And yes, making 18.04 default is good.

**Comment by cchadowitz-pf** [comment]
Awesome! I've found that this is actually an issue in OpenBLAS v0.2.20 and is fixed in later versions, but Ubuntu 18.04 ships with v0.2.20 and no updates. So one solution I've found is to install a later version of openblas (from say 19.10). If you still have a test environment to try this build, can you try installing these two .debs with `sudo apt-get install ./package-name.deb`?
http://launchpadlibrarian.net/410583809/libopenblas-base_0.3.5+ds-2_amd64.deb
http://launchpadlibrarian.net/410583808/libopenblas-dev_0.3.5+ds-2_amd64.deb

And then try the build again (with both caffe and dlib enabled)?

**Comment by beniz** [comment]
Hi, I was able to build the branch successfully by installing the two `.deb` files. It's fine with me to simply say it in the `README.md` file. 

FYI, I still had to comment out `dliblib.cc:183` due to the error with `spdlog`. You may have fixed that elsewhere though IIRC.

**Comment by cchadowitz-pf** [comment]
Awesome - I believe I fixed the spdlog error in my other PR, but I added it here as well. Also updated the README.md accordingly. Thanks again!

**Pull request merged**
