### PR TITLE
Dlib version update and regression fixes

### PR DESCRIPTION
**Pull request by cchadowitz-pf**
Update to fix some dlib regressions, and update the dlib version (which also fixes one new issue with opencv4).

This should be merged after https://github.com/jolibrain/deepdetect/pull/1448.

### CODE REVIEW

**Comment by fantes** [comment]
@mergifyio rebase

**Comment by fantes** [comment]
Hi

I just pushed some code formatting and rebasing

**Comment by beniz** [comment]
@cchadowitz-pf Hello, let's squash the commits and rebase !

**Comment by cchadowitz-pf** [comment]
> @cchadowitz-pf Hello, let's squash the commits and rebase !

I'm not sure if I did the squash+rebase right.....I suspect not based on what github is showing under 'files changed' for this PR.....

**Comment by Bycob** [comment]
@cchadowitz-pf I rebased your branch

If you want to add modifications you should override your local branch first with
```
git pull --rebase -Xtheirs
```
(if it does not work immediatly, delete your local branch and fetch it again)

**Comment by cchadowitz-pf** [comment]
Thanks @Bycob ! That looks great to me. I don't have any further changes for this dlib PR. I can't see what the GPU build error is but if it has to do with these changes please let me know and I'll take a look.

**Comment by cchadowitz-pf** [comment]
@Bycob not sure if you changed something but seems like all the checks have now passed?

**Review by Bycob — APPROVED** [review]

**Review by fantes — APPROVED** [review]

**Pull request merged**
