### PR TITLE
[FIX] image -> single target regression

### PR DESCRIPTION
**Pull request by fantes**
this PR fixes loss used when single target regression is used, previously it was working only with normalized values (or was meant to work only with normalized values, but has never been tested AFAIK)
option is parameters.mlllib.loss    
values are 
- "L1" (smoothL1 with smoothing when error < 10-2) , 
- "L2" (euclidean loss) [default],  
- "sigmoid" (sigmoidcrossentropyloss), to be used only for values between 0 and 1

three options have been tested OK

### CODE REVIEW

**Comment by beniz** [comment]
Thanks, can you squash / cleanup commits before merge ? Ideally, commit https://github.com/jolibrain/deepdetect/pull/738/commits/9939ccd7ac233fafcbd89ce5faf56e33b187aa52 should go elsewhere, if possible.

**Comment by beniz** [comment]
Two remarks:
- Sigmoid CE loss was used for multi-label classification, are we sure we want to remove it ?
- Do we want an option for using L1 instead of MSE when useful ?

**Comment by fantes** [comment]
> Two remarks:
> 
>     * Sigmoid CE loss was used for multi-label classification, are we sure we want to remove it ?

sigmoidCE is still the default for multi label, this fix only applies for single label

 
>     * Do we want an option for using L1 instead of MSE when useful ?

why not, but L1 in caffe needs more work, as it has to be implemented using several layers, maybe e can do this later if needed. as a workaround, smooth l1 can be added quickly.

**Comment by fantes** [comment]
> Thanks, can you squash / cleanup commits before merge ? Ideally, commit [9939ccd](https://github.com/jolibrain/deepdetect/commit/9939ccd7ac233fafcbd89ce5faf56e33b187aa52) should go elsewhere, if possible.

done

**Comment by beniz** [comment]
Thanks, can you add an image regression call or at least the relevant options that need to be set + basic input dataset format, FTR so that we can point to the PR.

**Pull request merged**
