### PR TITLE
Removed extra section that subtracted mean scalar values from the dat…

### PR DESCRIPTION
**Pull request by cchadowitz-pf**
…um after it was already subtracted from the Mat before it was converted to a datum.

### CODE REVIEW

**Comment by beniz** [comment]
Hi, thanks. So in fact we opted for reverting our bad commit. We figured that using `cv::subtract` before the conversion to `caffe::Datum` could yield erroneous results. This is because the Datum conversion from caffe (io.cpp / `CVMatToDatum`) uses an 8bit conversion per pixel value. With potential negative values (due to early mean subtraction), this would try to store the value into an unsigned int8...

**Comment by cchadowitz-pf** [comment]
Ahh I see. But couldn't the per-pixel subtraction still produce negative values (at least stored in a float, but still negative)? What's the appropriate behavior in the case of a negative value after subtracting the mean? Clamping to 0, leaving it as a negative, or taking the absolute value?
```
float datum_element = static_cast<float>(static_cast<uint8_t>(datum.data()[data_index]));	
datum.add_float_data(datum_element - _mean[c]);
```

Thanks!

**Comment by beniz** [comment]
Since it's stored in the float array, that's how it reaches the net's first layer, and this is fine.

**Comment by cchadowitz-pf** [comment]
So it's fine for the net's first layer to take in negative values (assuming that's what it's been trained with)? Got it 👍

**Pull request closed without merging**
